### ISSUE TITLE
Module compiled with Swift 4.2 cannot be imported in Swift 4.1.2:

### ISSUE THREAD

**Issue by bhushanrocks412** [easebuzz/paywitheasebuzz-ios-lib#1]
Module compiled with Swift 4.2 cannot be imported in Swift 4.1.2: /Users/rahulparab/Downloads/paywitheasebuzz-ios-lib-master/PaywithEasebuzzSample/Easebuzz.framework/Modules/Easebuzz.swiftmodule/x86_64.swiftmodule

getting this error, how to resolve this

**Comment by pavanjadhav1412** [comment]
Kit now updated

**Comment by bhushanrocks412** [comment]
thank you
